In [6]:
import numpy as np

# generate some linear-looking data
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

In [7]:
# compute theta using the normal equation
X_b = np.c_[np.ones((100, 1)), X]  # add x0 = 1 to each instance
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

In [8]:
# print values of theta 0 and theta 1
theta_best

array([[4.1408547 ],
       [3.02130891]])

# Linear Regression

In [10]:
# import the model
from sklearn.linear_model import LinearRegression

# initialize the model
lin_reg = LinearRegression()

# fit the model
lin_reg.fit(X,y)

# print intercept and coefficient
lin_reg.intercept_, lin_reg.coef_

(array([4.1408547]), array([[3.02130891]]))

In [11]:
# least squares
theta_best_svd, residuals, rank, s = np.linalg.lstsq(X_b, y, rcond=1e-6)

In [12]:
theta_best_svd

array([[4.1408547 ],
       [3.02130891]])

In [13]:
# compute the psuedoinverse
np.linalg.pinv(X_b).dot(y)


array([[4.1408547 ],
       [3.02130891]])

Important note: the Singular Value Decomposition (SVD) approach used by sklearn's linear regression class is about O(n sqaured). Be warned that when the number of features doubles, the computation time increases by roughly four times.

Both the normal equation and SVD get very slow when the number of features is large (100k), however, they are both linear with regard to number of instances in the training set so they can handle large training sets as long as those sets can fit in memory.

# Gradient Descent